src/IFS.Web/Areas/Administration/Controllers/FilesController.cs
// ******************************************************************************
//  © 2016 Sebastiaan Dammann - damsteen.nl
// 
//  File:           : FilesController.cs
//  Project         : IFS.Web
// ******************************************************************************

using System.Collections.Generic;
using System.Threading.Tasks;

using IFS.Web.Core;
using IFS.Web.Core.Upload;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using IFS.Web.Areas.Administration.Models;

using IFS.Web.Models;

namespace IFS.Web.Areas.Administration.Controllers;

[Authorize(KnownPolicies.Administration, AuthenticationSchemes = KnownAuthenticationScheme.AdministrationScheme)]
[Area(nameof(Administration))]
public sealed class FilesController : Controller {
    private readonly IUploadedFileRepository _uploadedFileRepository;

    public FilesController(IUploadedFileRepository uploadedFileRepository) {
        this._uploadedFileRepository = uploadedFileRepository;
    }

    // GET: /<controller>/
    public async Task<IActionResult> Index() {
        IList<UploadedFile> allFiles = await this._uploadedFileRepository.GetFiles();

        FilesOverviewModel model = new FilesOverviewModel(allFiles);
        return this.View(model);
    }

    public async Task<IActionResult> Log(FileIdentifier id) {
        UploadedFile? file = await this._uploadedFileRepository.GetFile(id);

        if (file == null) {
            return this.NotFound();
        }

        return this.View(file);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(FileIdentifier id) {
        this._uploadedFileRepository.Delete(id);

        return this.RedirectToAction("Index");
    }
}

src/IFS.Web/Areas/Administration/Controllers/UploadLinkController.cs
// ******************************************************************************
//  © 2016 Sebastiaan Dammann - damsteen.nl
// 
//  File:           : UploadLinkController.cs
//  Project         : IFS.Web
// ******************************************************************************

using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using IFS.Web.Core;
using IFS.Web.Core.ModelFactory;
using IFS.Web.Core.Upload;
using IFS.Web.Framework.Filters;
using IFS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace IFS.Web.Areas.Administration.Controllers;

[Authorize(KnownPolicies.Administration, AuthenticationSchemes = KnownAuthenticationScheme.AdministrationScheme)]
[Area(nameof(Administration))]
public class UploadLinkController : Controller {
    private readonly IFileStore _fileStore;
    private readonly IFileWriter _fileWriter;

    public UploadLinkController(IFileStore fileStore, IFileWriter fileWriter) {
        this._fileStore = fileStore;
        this._fileWriter = fileWriter;
    }

    // GET: /<controller>/
    [HttpGet]
    [AutoFillSenderInformation]
    public IActionResult Index() {
        UploadLinkModel model = UploadModelFactory.CreateLink();
        return this.View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Index(IFormCollection form) {
        UploadLinkModel model = UploadModelFactory.CreateLink();

        if (!await this.TryUpdateModelAsync(model)) {
            return this.View(model);
        }

        await this.ReserveUploadAsync(model);

        return this.View("LinkCreated", model);
    }

    private async Task ReserveUploadAsync(UploadLinkModel model) {
        CancellationToken cancellationToken = this.HttpContext.RequestAborted;
        StoredMetadata metadata = new StoredMetadata {
            Expiration = model.Expiration,
            UploadedOn = DateTime.UtcNow,
            IsReservation = true,
            Sender = model.Sender
        };

        // Ensure no empty contact information
        if (model.Sender != null && String.IsNullOrEmpty(model.Sender.Name) && String.IsNullOrEmpty(model.Sender.EmailAddress)) {
            metadata.Sender = null;
        }

        // Write away
        await using var fileStream =
            this._fileWriter.OpenWriteStream(this._fileStore.GetMetadataFile(model.FileIdentifier));
        await using var sw = new StreamWriter(fileStream, Encoding.UTF8);
        await sw.WriteAsync(metadata.Serialize()).ConfigureAwait(false);

        await fileStream.FlushAsync(cancellationToken).ConfigureAwait(false);
    }
}

src/IFS.Web/Areas/Administration/Views/Files/Index.cshtml
@using Humanizer
@using IFS.Web.Core.Upload
@model FilesOverviewModel

@{
    ViewBag.Title = "Uploaded file overview";
}

<ifs-page-title>@ViewBag.Title</ifs-page-title>

@{
    var sortedFiles = Model!.Files.OrderBy(x => x.Metadata.OriginalFileName);
}


<table class="table table-striped">
    <thead>
    <tr>
        <th>Type</th>
        <th>ID</th>
        <th>File name</th>
        <th>Last downloaded on</th>
        <th>Uploaded / Created at</th>
        <th>By</th>
        <th>Expires</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var file in sortedFiles) {
        var lastAccess = file.Metadata.Access.LogEntries.OrderByDescending(x => x.Timestamp).FirstOrDefault()?.Timestamp.Humanize() ?? "Never";

        if (!file.IsUnusedReservation) {
            <tr>
                <td>
                    @if (!file.Metadata.IsReservation) {
                        <span class="fa-solid fa-file tip" title="This is an uploaded file via password authentication"></span>
                    } else {
                        <span class="con-file-reservation tip" title="This is an uploaded file via an invitation">
                            <span class="fa-solid fa-file"></span>
                            <span class="fa fa-clock"></span>
                        </span>
                    }
                </td>
                <td><code>@file.Id</code></td>
                <td>
                    <a asp-route="DownloadFile" asp-route-id="@file.Id">@file.Metadata.OriginalFileName</a>
                </td>
                <td>
                    <a asp-action="Log" asp-route-id="@file.Id">@lastAccess</a>
                </td>
                <td>
                    @file.Metadata.UploadedOn.Humanize()
                </td>
                <td>
                    @{
                        ContactInformation? sender = file.Metadata.Sender;

                        if (sender != null) {
                            string? name = String.IsNullOrEmpty(sender.Name) ? sender.EmailAddress : sender.Name;
                            bool nameOnly = !String.IsNullOrEmpty(sender.EmailAddress);

                            if (nameOnly) {
                                @name
                            } else {
                                <a href="mailto:@sender.EmailAddress">@name</a>
                            }
                        } else {
                            <i>Not available</i>
                        }
                    }
                </td>
                <td>
                    @file.Metadata.Expiration.Humanize() (@file.Metadata.Expiration.ToString("g"))
                </td>
                <td>
                    <form asp-action="Delete" asp-route-id="@file.Id" asp-antiforgery="true">
                        <button class="btn btn-sm btn-danger">
                            <span class="fa-solid fa-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
         } else {
            <tr>
                <td>
                    <span class="fa-solid fa-clock tip" title="This is an unused upload invitation link"></span>
                </td>
                <td><code>@file.Id</code></td>
                <td>
                    (no file uploaded yet)
                </td>
                <td>
                    (reservation)
                </td>
                <td>
                    @file.Metadata.UploadedOn.Humanize()
                </td>
                <td>
                    @{
                        ContactInformation? sender = file.Metadata.Sender;

                        if (sender != null) {
                            string? name = String.IsNullOrEmpty(sender.Name) ? sender.EmailAddress : sender.Name;
                            bool nameOnly = String.IsNullOrEmpty(sender.EmailAddress);

                            if (nameOnly) {
                                @name
                            } else {
                                <a href="mailto:@sender.EmailAddress">@name</a>
                            }
                        } else {
                            <i>Not available</i>
                        }
                    }
                </td>
                <td>
                    @file.Metadata.Expiration.Humanize() (@file.Metadata.Expiration.ToString("g"))
                </td>
                <td>
                    <form asp-action="Delete" asp-route-id="@file.Id" asp-antiforgery="true">
                        <button class="btn btn-sm btn-danger">
                            <span class="fa-solid fa-trash"></span>
                        </button>
                    </form>
                </td>
            </tr>
         }
    }
        
    @if (Model.Files.Count == 0) {
        <tr>
            <td colspan="8">
                <strong>Its empty!</strong> No files have been uploaded yet.
            </td>
        </tr>
    }
    </tbody>
</table>

<div>
    <a class="btn btn-default" asp-controller="UploadLink" asp-action="Index" asp-area="Administration">
        <span class="fa-solid fa-link"></span>
        Create upload link
    </a>

    <partial name="_LogOffButton"/>
</div>

@section scripts {
    <script>window.app.setTooltips('.tip');</script>
}

src/IFS.Web/Areas/Administration/Views/Files/Log.cshtml
@using System.Linq
@using Humanizer
@model IFS.Web.Core.Upload.UploadedFile

@{
    ViewBag.Title = $"Access log of {Model!.Metadata.OriginalFileName}";

    var accessLog = Model.Metadata.Access;
}

<ifs-page-title>Access log</ifs-page-title>
<h2>@Model.Metadata.OriginalFileName</h2>

@if (accessLog.LogEntries.Count > 0) {
    <table class="table table-striped">
        <thead>
        <tr>
            <th>IP address</th>
            <th>Timestamp</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var access in accessLog.LogEntries.OrderBy(x => x.Timestamp)) {
            <tr>
                <td>@(access.IpAddress ?? "Unknown")</td>
                <td>@access.Timestamp.ToString("s") (@access.Timestamp.Humanize())</td>
            </tr>
        }
        </tbody>
    </table>
} else {
    <div class="alert alert-info">
        <strong>Sorry...</strong> this file has never been downloaded yet!
    </div>
}
<p>
    <a asp-action="Index" class="btn btn-default">Back to overview</a>
</p>