src/IFS.Web/Areas/Administration/Controllers/FilesController.cs
// ******************************************************************************
//  © 2016 Sebastiaan Dammann - damsteen.nl
// 
//  File:           : FilesController.cs
//  Project         : IFS.Web
// ******************************************************************************

using System.Collections.Generic;
using System.Threading.Tasks;

using IFS.Web.Core;
using IFS.Web.Core.Upload;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using IFS.Web.Areas.Administration.Models;

using IFS.Web.Models;

namespace IFS.Web.Areas.Administration.Controllers;

[Authorize(KnownPolicies.Administration, AuthenticationSchemes = KnownAuthenticationScheme.AdministrationScheme)]
[Area(nameof(Administration))]
public sealed class FilesController : Controller {
    private readonly IUploadedFileRepository _uploadedFileRepository;

    public FilesController(IUploadedFileRepository uploadedFileRepository) {
        this._uploadedFileRepository = uploadedFileRepository;
    }

    // GET: /<controller>/
    public async Task<IActionResult> Index() {
        IList<UploadedFile> allFiles = await this._uploadedFileRepository.GetFiles();

        FilesOverviewModel model = new FilesOverviewModel(allFiles);
        return this.View(model);
    }

    public async Task<IActionResult> Log(FileIdentifier id) {
        UploadedFile? file = await this._uploadedFileRepository.GetFile(id);

        if (file == null) {
            return this.NotFound();
        }

        return this.View(file);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(FileIdentifier id) {
        this._uploadedFileRepository.Delete(id);

        return this.RedirectToAction("Index");
    }
}

src/IFS.Web/Areas/Administration/Controllers/UploadLinkController.cs
// ******************************************************************************
//  © 2016 Sebastiaan Dammann - damsteen.nl
// 
//  File:           : UploadLinkController.cs
//  Project         : IFS.Web
// ******************************************************************************

using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using IFS.Web.Core;
using IFS.Web.Core.ModelFactory;
using IFS.Web.Core.Upload;
using IFS.Web.Framework.Filters;
using IFS.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace IFS.Web.Areas.Administration.Controllers;

[Authorize(KnownPolicies.Administration, AuthenticationSchemes = KnownAuthenticationScheme.AdministrationScheme)]
[Area(nameof(Administration))]
public class UploadLinkController : Controller {
    private readonly IFileStore _fileStore;
    private readonly IFileWriter _fileWriter;

    public UploadLinkController(IFileStore fileStore, IFileWriter fileWriter) {
        this._fileStore = fileStore;
        this._fileWriter = fileWriter;
    }

    // GET: /<controller>/
    [HttpGet]
    [AutoFillSenderInformation]
    public IActionResult Index() {
        UploadLinkModel model = UploadModelFactory.CreateLink();
        return this.View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Index(IFormCollection form) {
        UploadLinkModel model = UploadModelFactory.CreateLink();

        if (!await this.TryUpdateModelAsync(model)) {
            return this.View(model);
        }

        await this.ReserveUploadAsync(model);

        return this.View("LinkCreated", model);
    }

    private async Task ReserveUploadAsync(UploadLinkModel model) {
        CancellationToken cancellationToken = this.HttpContext.RequestAborted;
        StoredMetadata metadata = new StoredMetadata {
            Expiration = model.Expiration,
            UploadedOn = DateTime.UtcNow,
            IsReservation = true,
            Sender = model.Sender
        };

        // Ensure no empty contact information
        if (model.Sender != null && String.IsNullOrEmpty(model.Sender.Name) && String.IsNullOrEmpty(model.Sender.EmailAddress)) {
            metadata.Sender = null;
        }

        // Write away
        await using var fileStream =
            this._fileWriter.OpenWriteStream(this._fileStore.GetMetadataFile(model.FileIdentifier));
        await using var sw = new StreamWriter(fileStream, Encoding.UTF8);
        await sw.WriteAsync(metadata.Serialize()).ConfigureAwait(false);

        await fileStream.FlushAsync(cancellationToken).ConfigureAwait(false);
    }
}

src/IFS.Web/Areas/Administration/Views/UploadLink/Index.cshtml
@model IFS.Web.Models.UploadLinkModel

@{
    ViewBag.Title = "Create upload hyperlink";
}

<ifs-page-title>@ViewBag.Title</ifs-page-title>

<p>
    Create an upload link so an external party can upload a file for you. Give the link an
    expiration date so the file will be automatically removed from the server after upload.
</p>

<form method="post">
    <input asp-for="FileIdentifier" type="hidden" />

    <div class="form-floating mb-3">
        <select asp-for="Expiration" asp-items="Model!.AvailableExpiration" class="form-select"></select>
        <label asp-for="Expiration"></label>
    </div>
    <hr />

    @{
        await Html.RenderPartialAsync("_ContactInformationEntry", Model);
    }

    <p>
        <button class="btn btn-primary">
            <span class=" fa-solid fa-upload"></span> Create link
        </button>

        <a asp-controller="Files" asp-action="Index" asp-area="Administration" class="btn btn-link">Go back</a>
    </p>
</form>

@section scripts {
    <script>
        window.app.contactInformationPersistence.initialize(
            '@Html.IdFor(x => x.Sender!.Name)',
            '@Html.IdFor(x => x.Sender!.EmailAddress)'
        );
    </script>
}

src/IFS.Web/Areas/Administration/Views/UploadLink/LinkCreated.cshtml
@using System.Text.Encodings.Web
@model IFS.Web.Models.UploadLinkModel

@{
    ViewBag.Title = "Upload link created";
}

<ifs-page-title>@ViewBag.Title</ifs-page-title>

<p>
    Your upload link has been created and is valid until @Model!.Expiration.ToString("f"). You can share the upload
    link with another party which can use it to upload one file.
</p>


@{
    string uploadLink = this.Url.RouteUrl("UploadFile", new { id = Model.FileIdentifier }, this.Context.Request.Scheme)!;
    string downloadLink = this.Url.RouteUrl("DownloadFile", new { id = Model.FileIdentifier }, this.Context.Request.Scheme)!;
}

<p>
    Upload link to share: <input type="text" value="@uploadLink" class="form-control input-lg" id="upload-link" readonly="readonly" />
</p>

<p>
    After the upload has been completed, you will be able to download the file from:
    <input type="text" value="@downloadLink" class="form-control input-sm" id="download-link" readonly="readonly" />
</p>

@section scripts {
    <script>
        (function() {
            // Replace URL for easy copying
            if ('replaceState' in history) {
                history.replaceState({}, null, '@JavaScriptEncoder.Default.Encode(uploadLink)');
            }

            var doSelect = function() {
                this.select();
            };

            document.getElementById('upload-link').addEventListener('mouseup', doSelect);
            document.getElementById('download-link').addEventListener('mouseup', doSelect);
        })();
    </script>
}

<p>
    <a asp-controller="Files" class="btn btn-primary">Go back</a>
</p>